from ipn.models.Event import Event

def create_event_from_message(message_dict, message):
  Event.objects.create(
    title = message_dict.get('TITLE', None),
    notice_date = message_dict.get('NOTICE_DATE', None),
    notice_type = message_dict.get('NOTICE_TYPE', None),
    next_point_ra = message_dict.get('NEXT_POINT_RA', None),
    next_point_dec = message_dict.get('NEXT_POINT_DEC', None),
    slew_time = message_dict.get('SLEW_TIME', None),
    slew_date = message_dict.get('SLEW_DATE', None),
    sun_postn = message_dict.get('SUN_POSTN', None),
    sun_dist = message_dict.get('SUN_DIST', None),
    moon_postn = message_dict.get('MOON_POSTN', None),
    moon_dist = message_dict.get('MOON_DIST', None),
    gal_coords = message_dict.get('GAL_COORDS', None),
    ecl_coords = message_dict.get('ECL_COORDS', None),
    trigger_id = message_dict.get('TRIGGER_ID', None),
    trigger_num = message_dict.get('TRIGGER_NUM', None),
    trigger_date = message_dict.get('TRIGGER_DATE', None),
    trigger_time = message_dict.get('TRIGGER_TIME', None),
    sequence_num = message_dict.get('SEQUENCE_NUM', None),
    grb_inten = message_dict.get('GRB_INTEN', None),
    grb_time = message_dict.get('GRB_TIME', None),
    grb_date = message_dict.get('GRB_DATE', None),
    prob_ns = message_dict.get('PROB_NS', None),
    prob_remnant = message_dict.get('PROB_REMNANT', None),
    prob_bns = message_dict.get('PROB_BNS', None),
    prob_nsbh = message_dict.get('PROB_NSBH', None),
    prob_bbh = message_dict.get('PROB_BBH', None),
    prob_massgap = message_dict.get('PROB_MASSGAP', None),
    prob_terres = message_dict.get('PROB_TERRES', None),
    group_type = message_dict.get('GROUP_TYPE', None),
    search_type = message_dict.get('SEARCH_TYPE', None),
    pipeline_type = message_dict.get('PIPELINE_TYPE', None),
    far = message_dict.get('FAR', None),
    skymap_fits_url = message_dict.get('SKYMAP_FITS_URL', None),
    eventpage_url = message_dict.get('EVENTPAGE_URL', None),
    comments = message_dict.get('COMMENTS', None),
    misc = message_dict.get('MISC', None),
    message = message,
  )
