# Generated by Django 4.2.2 on 2023-06-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0002_lvc_preliminary_test_lvc_preliminary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integral_Pointing_Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('notice_date', models.DateTimeField()),
                ('notice_type', models.CharField()),
                ('next_point_ra', models.CharField()),
                ('next_point_dec', models.CharField()),
                ('slew_time', models.CharField()),
                ('slew_date', models.CharField()),
                ('sun_postn', models.CharField()),
                ('sun_dist', models.CharField()),
                ('moon_postn', models.CharField()),
                ('moon_dist', models.CharField()),
                ('gal_coords', models.CharField()),
                ('ecl_coords', models.CharField()),
                ('comments', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Lvc_Retraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('notice_date', models.DateTimeField()),
                ('notice_type', models.CharField()),
                ('trigger_num', models.CharField()),
                ('trigger_date', models.DateField()),
                ('trigger_time', models.CharField()),
                ('sequence_num', models.BigIntegerField()),
                ('trigger_id', models.CharField()),
                ('misc', models.CharField()),
                ('comments', models.CharField()),
            ],
        ),
    ]
