# Generated by Django 4.2.2 on 2023-06-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0003_integral_pointing_direction_lvc_retraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='notice_type',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
