# Generated by Django 4.2.2 on 2023-06-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0006_test_lvc_initial_skymap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integral_pointing_direction',
            name='notice_date',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lvc_preliminary',
            name='notice_date',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lvc_retraction',
            name='notice_date',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='test_lvc_initial_skymap',
            name='notice_date',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='test_lvc_preliminary',
            name='notice_date',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
