# Generated by Django 4.2.2 on 2023-06-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0007_alter_integral_pointing_direction_notice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lvc_preliminary',
            name='trigger_date',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lvc_retraction',
            name='trigger_date',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='test_lvc_initial_skymap',
            name='trigger_date',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='test_lvc_preliminary',
            name='trigger_date',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
