# Generated by Django 4.2.2 on 2023-06-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0008_alter_lvc_preliminary_trigger_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integral_pointing_direction',
            name='ipn_message_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ipn.message'),
        ),
        migrations.AlterField(
            model_name='lvc_preliminary',
            name='ipn_message_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ipn.message'),
        ),
        migrations.AlterField(
            model_name='lvc_retraction',
            name='ipn_message_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ipn.message'),
        ),
        migrations.AlterField(
            model_name='test_lvc_initial_skymap',
            name='ipn_message_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ipn.message'),
        ),
        migrations.AlterField(
            model_name='test_lvc_preliminary',
            name='ipn_message_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ipn.message'),
        ),
    ]
