# Generated by Django 4.2.2 on 2023-06-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0011_rename_ipn_message_integral_pointing_direction_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lvc_preliminary',
            name='skymap',
            field=models.BinaryField(null=True),
        ),
    ]
