# Generated by Django 4.2.2 on 2023-06-28 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0013_integral_spi_acs_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Integral_Spi_Acs_Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, null=True)),
                ('notice_date', models.CharField(blank=True, default=None, null=True)),
                ('notice_type', models.CharField(blank=True, default=None, null=True)),
                ('trigger_num', models.CharField(blank=True, default=None, null=True)),
                ('trigger_date', models.CharField(blank=True, default=None, null=True)),
                ('trigger_time', models.CharField(blank=True, default=None, null=True)),
                ('grb_inten', models.CharField(blank=True, default=None, null=True)),
                ('grb_time', models.CharField(blank=True, default=None, null=True)),
                ('grb_date', models.CharField(blank=True, default=None, null=True)),
                ('comments', models.CharField(blank=True, default=None, null=True)),
                ('message', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ipn.message')),
            ],
        ),
    ]
