# Generated by Django 4.2.2 on 2023-06-28 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0015_lvc_update_skymap'),
    ]

    operations = [
        migrations.AddField(
            model_name='lvc_preliminary',
            name='lvc_Retraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipn.lvc_retraction'),
        ),
    ]
