# Generated by Django 4.2.2 on 2023-06-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0016_lvc_preliminary_lvc_retraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='lvc_preliminary',
            name='event_date_utc',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
