# Generated by Django 4.2.2 on 2023-06-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0018_integral_spi_acs_trigger_event_date_utc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='event_date_utc',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
