# Generated by Django 4.2.2 on 2023-06-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0019_message_event_date_utc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lvc_preliminary',
            old_name='lvc_Retraction',
            new_name='lvc_retraction',
        ),
    ]
