# Generated by Django 4.2.2 on 2023-06-29 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0020_rename_lvc_retraction_lvc_preliminary_lvc_retraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, null=True)),
                ('notice_date', models.CharField(blank=True, default=None, null=True)),
                ('notice_type', models.CharField(blank=True, default=None, null=True)),
                ('next_point_ra', models.CharField(blank=True, default=None, null=True)),
                ('next_point_dec', models.CharField(blank=True, default=None, null=True)),
                ('slew_time', models.CharField(blank=True, default=None, null=True)),
                ('slew_date', models.CharField(blank=True, default=None, null=True)),
                ('sun_postn', models.CharField(blank=True, default=None, null=True)),
                ('sun_dist', models.CharField(blank=True, default=None, null=True)),
                ('moon_postn', models.CharField(blank=True, default=None, null=True)),
                ('moon_dist', models.CharField(blank=True, default=None, null=True)),
                ('gal_coords', models.CharField(blank=True, default=None, null=True)),
                ('ecl_coords', models.CharField(blank=True, default=None, null=True)),
                ('trigger_id', models.CharField(blank=True, default=None, null=True)),
                ('trigger_num', models.CharField(blank=True, default=None, null=True)),
                ('trigger_date', models.CharField(blank=True, default=None, null=True)),
                ('trigger_time', models.CharField(blank=True, default=None, null=True)),
                ('sequence_num', models.BigIntegerField(blank=True, default=None, null=True)),
                ('prob_ns', models.CharField(blank=True, default=None, null=True)),
                ('prob_remnant', models.CharField(blank=True, default=None, null=True)),
                ('prob_bns', models.CharField(blank=True, default=None, null=True)),
                ('prob_nsbh', models.CharField(blank=True, default=None, null=True)),
                ('prob_bbh', models.CharField(blank=True, default=None, null=True)),
                ('prob_massgap', models.CharField(blank=True, default=None, null=True)),
                ('prob_terres', models.CharField(blank=True, default=None, null=True)),
                ('group_type', models.CharField(blank=True, default=None, null=True)),
                ('search_type', models.CharField(blank=True, default=None, null=True)),
                ('pipeline_type', models.CharField(blank=True, default=None, null=True)),
                ('grb_inten', models.CharField(blank=True, default=None, null=True)),
                ('grb_time', models.CharField(blank=True, default=None, null=True)),
                ('grb_date', models.CharField(blank=True, default=None, null=True)),
                ('far', models.CharField(blank=True, default=None, null=True)),
                ('misc', models.CharField(blank=True, default=None, null=True)),
                ('skymap_fits_url', models.CharField(blank=True, default=None, null=True)),
                ('eventpage_url', models.CharField(blank=True, default=None, null=True)),
                ('skymap', models.BinaryField(null=True)),
                ('event_date_utc', models.DateTimeField(blank=True, default=None, null=True)),
                ('comments', models.CharField(blank=True, default=None, null=True)),
                ('message', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ipn.message')),
            ],
        ),
    ]
